version: '3.9'

x-r-version:
  &r-version
  R_VERSION=4.1.0
  
x-bieulergy-git-repo:
  &bieulergy-git-repo
  https://github.com/montilab/bieulergy.git#dev

services:
  bieulergy:
    container_name: bieulergy
    image: montilab/bieulergy:latest
    build: 
      context: *bieulergy-git-repo
      dockerfile: Dockerfile.shiny
      args:
        - *r-version
    restart: always
    ports:
      - 1234:3838