name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:4.0.0-ubuntu18.04
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            apt-utils \
            libglpk-dev \
            libcurl4-openssl-dev \
            libxml2-dev \
            libssl-dev && \
            apt-get clean && \
            rm -rf /var/lib/apt/lists/*

      - name: Install bieulergy
        run: |
          install.packages('devtools')
          devtools::install_github("montilab/hypeR")
          devtools::install('.', dependencies=TRUE)
        shell: Rscript {0}

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: rcmdcheck::rcmdcheck(args=c("--no-manual", "--no-build-vignettes"), build_args=c("--no-build-vignettes"), error_on="error", check_dir="check")
        shell: Rscript {0}

      # Push docker image to docker hub  
      #- uses: docker/build-push-action@v1
      #  with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}
      #    repository: montilab/bieulergy
      #    tag_with_ref: true
      #    tag_with_sha: true
      #    tags: latest

      #- name: Install pkgdown and vignette dependencies
      #  run: |
      #    install.packages('pkgdown')
      #    install.packages('reactable')
      #    install.packages('biomaRt', repos=BiocManager::repositories())
      #  shell: Rscript {0}

      #- name: Build pkgdown
      #  run: |
      #     PATH=$PATH:$HOME/bin/ Rscript -e 'pkgdown::build_site("."); file.copy("media", "docs", recursive=TRUE)'
      # deploy needs rsync? Seems so.
      #- name: Install deploy dependencies
      #  run: |
      #    apt-get update
      #    apt-get -y install rsync
      #- name: Deploy 🚀
      #  uses: JamesIves/github-pages-deploy-action@releases/v3
      #  with:
      #    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #    BRANCH: gh-pages # The branch the action should deploy to.
      #    FOLDER: docs # The folder the action should deploy.
